core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import CustomTemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.urls import path, include
import os

urlpatterns = [
    path(os.getenv("ADMIN_URL"), admin.site.urls),
    path("", CustomTemplateView.as_view(), name="home"),
    path("resumes/", include("resumes.urls")),
    path("users/", include("users.urls")),
    path("jobs/", include("jobs.urls")),
    path("companies/", include("companies.urls")),
    path("accounts/", include("allauth.urls")),
    path("educations/", include("educations.urls")),
    path("works/", include("works.urls")),
    path("projects/", include("projects.urls")),
    path("api/v1/resumes/",include("resumes.urls")),
    path("about/", include("about.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

educations/urls.py
from django.urls import path
from .views import EducationUpdateView, EducationDeleteView

app_name = "educations"

urlpatterns = [
    path("<pk>/edit", EducationUpdateView.as_view(), name="edu_edit"),
    path("<pk>/delete", EducationDeleteView.as_view(), name="edu_delete"),
]

resumes/urls.py
from django.urls import path
from .views import (
    ResumeArea,
    ResumeListView,
    ResumeCreateView,
    ResumeUpdateView,
    ResumeDeleteView,
    TotalListView,
    generate_pdf_1,
    generate_pdf_2,
    generate_pdf_3,
    update_positions,
    UpdateStyleView,
    update_template,
)
from educations.views import EducationCreateView, EducationListView
from works.views import WorkCreateView, WorkListView
from projects.views import ProjectCreateView, ProjectListView

app_name = "resumes"

urlpatterns = [
    path("", ResumeArea.as_view(), name="index"),
    path("create/", ResumeCreateView.as_view(), name="create"),
    path("edit/<pk>", ResumeUpdateView.as_view(), name="edit"),
    path("delete/<pk>", ResumeDeleteView.as_view(), name="delete"),
    path("resume/<int:resume_id>/pdf_1/", generate_pdf_1, name="generate_pdf_1"),
    path("resume/<int:resume_id>/pdf_2/", generate_pdf_2, name="generate_pdf_2"),
    path("resume/<int:resume_id>/pdf_3/", generate_pdf_3, name="generate_pdf_3"),
    path("total/<int:resume_id>", TotalListView.as_view(), name="total"),
    path("update_positions/", update_positions, name="update_positions"),
    path("<pk>/education/", EducationCreateView.as_view(), name="education"),
    path("<pk>/educations/", EducationListView.as_view(), name="educations"),
    path("<pk>/work/", WorkCreateView.as_view(), name="work"),
    path("<pk>/works/", WorkListView.as_view(), name="works"),
    path("<pk>/project/", ProjectCreateView.as_view(), name="project"),
    path("<pk>/projects/", ProjectListView.as_view(), name="projects"),
    path("update_style/<int:resume_id>", UpdateStyleView.as_view(), name="update_style"),
    path("<int:resume_id>/update_template", update_template, name="update_template"),
    path("<pk>/", ResumeListView.as_view(), name="show"),
]

educations/models.py
from django.db import models
from django.utils import timezone
from positions.fields import PositionField
from resumes.models import Resume


class EducationManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted_at=None)


class Education(models.Model):
    DEGREE_CHOICES = [
        ("1", "高中職以下"),
        ("2", "高中職"),
        ("3", "專科"),
        ("4", "學士"),
        ("5", "碩士"),
        ("6", "博士"),
        ("7", "肄業"),
    ]

    resume = models.ForeignKey(
        Resume, on_delete=models.CASCADE, related_name="educations"
    )
    school_name = models.CharField(max_length=100)
    major = models.CharField(max_length=100)
    degree = models.CharField(max_length=1, choices=DEGREE_CHOICES)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    posit = PositionField(collection="resume")

    objects = models.Manager()
    edu_objects = EducationManager()
    
    class Meta:
        ordering = ['posit']
    
    def delete(self, *args, **kwargs):
        self.deleted_at = timezone.now()
        self.save()

educations/forms.py
from django import forms
from .models import Education
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class EducationForm(forms.ModelForm):
    start_date = forms.DateTimeField(
        input_formats=["%Y-%m"],
        widget=forms.DateInput(attrs={"type": "month"}),
        required=False,
    )
    end_date = forms.DateTimeField(
        input_formats=["%Y-%m"],
        widget=forms.DateInput(attrs={"type": "month"}),
        required=False,
    )
    field_labels = {
        "school_name": "校名",
        "major": "專業",
        "degree": "學位",
        "start_date": "入學時間",
        "end_date": "畢業時間",
    }

    class Meta:
        model = Education
        exclude = ["resume", "deleted_at", "created_at", "posit"]

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request", None)
        super().__init__(*args, **kwargs)
        for field_name, label in self.field_labels.items():
            self.fields[field_name].label = label

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get("start_date")
        end_date = cleaned_data.get("end_date")

        if start_date and end_date and start_date > end_date:
            raise ValidationError(_("入學時間不能晚於畢業時間"))

        return cleaned_data

educations/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from .models import Education
from resumes.models import Resume
from .forms import EducationForm
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
import rules

class EducationCreateView(PermissionRequiredMixin, CreateView):
    model = Education
    form_class = EducationForm
    template_name = 'educations/create.html'
    permission_required = "user_can_show"

    def dispatch(self, request, *args, **kwargs):
        resume_id = self.kwargs.get('pk')
        self.resume = get_object_or_404(Resume, pk=resume_id)
        if not rules.test_rule('is_education_user',request.user, self.resume):
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)
    
    def get_queryset(self):
        resume_id = self.kwargs['pk']
        return Education.objects.filter(resume_id=resume_id)

    def form_valid(self, form):
        form.instance.resume = self.resume
        messages.success(self.request, "新增成功")
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['resume_id'] = self.kwargs['pk']
        return context
    
    def get_success_url(self):
        resume_id = self.kwargs['pk']
        return reverse('resumes:educations', kwargs={'pk': resume_id})


class EducationListView(PermissionRequiredMixin, ListView):
    model = Education
    template_name = "educations/index.html"
    context_object_name = "educations"
    permission_required = "user_can_show"

    def dispatch(self, request, *args, **kwargs):
        resume_id = self.kwargs.get('pk')
        self.resume = get_object_or_404(Resume, pk=resume_id)
        if not rules.test_rule('is_education_user',request.user, self.resume):
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        resume_id = self.kwargs['pk']
        return Education.edu_objects.filter(resume_id=resume_id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['resume_id'] = self.kwargs['pk']
        return context


class EducationUpdateView(UpdateView):
    model = Education
    form_class = EducationForm
    template_name = "educations/update.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        education = self.get_object()
        context['resume_id'] = education.resume_id
        return context
    
    def dispatch(self, request, *args, **kwargs):
        education = self.get_object()
        resume = education.resume
        if not rules.test_rule("is_education_user", request.user, resume):
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)
    
    def get_success_url(self):
        return reverse_lazy('resumes:educations', kwargs={'pk': self.object.resume.pk})

    def form_valid(self, form):
        messages.success(self.request, "更新成功")
        self.object = form.save()
        return super().form_valid(form)


class EducationDeleteView(DeleteView):
    model = Education
    success_url = reverse_lazy("resumes:educations")

    def dispatch(self, request, *args, **kwargs):
        education = self.get_object()
        resume = education.resume
        if not rules.test_rule("is_education_user", request.user, resume):
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        messages.success(self.request, "刪除成功")
        return reverse_lazy('resumes:educations', kwargs={'pk': self.object.resume.pk})

templates/educations/create.html
{% extends 'frontend.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mx-auto max-w-lg mt-8">
        <div class="flex justify-center">
            <div class="w-full">
                <div class="header-bar flex justify-between items-center bg-user-blue text-white p-4 rounded-t-md">
                    <a href="{% url 'resumes:educations' resume_id %}">&#8592;Back</a>
                </div>
                <div class="card-body p-4 shadow-md mt-4">
                    <h3 class="text-lg font-semibold mb-4">新增教育</h3>
                    <form method="post" id="myForm" action="{% url 'resumes:education' resume_id %}">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="flex justify-end">
                        <button type="submit" class="user-sm-btn">提交</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/educations/index.html
{% extends 'frontend.html' %}
{% block content %}

    <div class="container mx-auto max-w-lg mt-8">
        <div class="header-bar flex justify-between items-center bg-user-blue text-white p-4 rounded-t-md mb-4">
            <a href="{% url 'resumes:show' pk=resume_id %}" class="text-white-600 hover:text-user-blue mr-4">&#8592;Back</a>
            <a href="{% url 'resumes:education' resume_id %}" class="edu text-white-600 hover:text-user-blue">&#43;</a>
        </div>
        <div class="card-body p-4 shadow-md">
            <h1 class="text-3xl font-bold mb-6">教育經驗</h1>
            {% if educations %}
                <ul>
                    {% for education in educations %}
                        <li class="flex justify-between items-center mb-4">
                            <div>
                                <strong>{{ education.school_name }} - {{ education.major }}</strong>
                                <p>學位：{{ education.get_degree_display }}</p>
                                <p>入學期間： {{ education.start_date |date:"Y年m月" }}--{{ education.end_date |date:"Y年m月" }}</p>
                                <hr>
                            </div>
                            <div class="flex space-x-2">
                                <button class="button user-sm-btn">
                                    <a href="{% url 'educations:edu_edit' education.id %}">編輯</a>
                                </button>
                                <form method="post" action="{% url 'educations:edu_delete' education.pk %}" onsubmit="return confirm('確定要刪除嗎？');">
                                    {% csrf_token %}
                                    <button type="submit" class="button user-sm-btn">刪除</button>
                                </form>
                            </div>
            
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>目前無教育經驗</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/educations/update.html
{% extends 'frontend.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mx-auto max-w-lg mt-8">
        <div class="flex justify-center">
            <div class="w-full">
                <div class="header-bar flex justify-start items-center bg-user-blue text-white p-4 rounded-t-md">
                    <a href="{% url 'resumes:educations' resume_id %}" class="text-white">&#8592;Back</a>
                </div>

                <div class="card-body p-4 shadow-md mt-4">
                    <h3 class="text-lg font-semibold mb-4">編輯教育經驗</h3>    
                    <form method="post" id="myForm" action="{% url 'educations:edu_edit' education.pk %}">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <div class="flex justify-end">
                        <button type="submit" class="user-sm-btn me-2">提交</button>
                        </form>
                        <form method="post" action="{% url 'educations:edu_delete' education.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="user-sm-btn">刪除</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}