companies/urls.py
from django.urls import path
from .views import (
    CompanyHomeView,
    CompanyLoginView,
    CompanyLogoutView,
    CompanyDetailView,
    CompanyUpdateView,
    CompanyRegisterView,
    CompanyPasswordChangeView,
    CompanyListView,
    CompanyInfoView,
    CollectCompanyView,
    JobApplicationsView,
    JobApplicationDetailView,
    MarkAsReadView,
    InterviewResultCreateView,
    FavoriteCompanyView,
    CompanyInterviewsCalendarView
)
from jobs import views as jobs

app_name = "companies"

urlpatterns = [
    path("", CompanyHomeView.as_view(), name="home"),
    path("list/", CompanyListView.as_view(), name="company_list"),
    path("info/<int:pk>/", CompanyInfoView.as_view(), name="company_info"),
    path("register/", CompanyRegisterView.as_view(), name="register"),
    path("login/", CompanyLoginView.as_view(), name="login"),
    path("logout/", CompanyLogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        CompanyPasswordChangeView.as_view(),
        name="password_change",
    ),
    path("<int:pk>/update/", CompanyUpdateView.as_view(), name="update"),
    path("<int:pk>/jobs/", jobs.IndexView.as_view(), name="jobs"),
    path("<int:pk>/create/", jobs.AddView.as_view(), name="jobs_create"),
    path("<int:pk>/applications/", JobApplicationsView.as_view(), name="applications"),
    path("<int:pk>/mark", MarkAsReadView.as_view(), name="mark"),
    path("<int:pk>/", CompanyDetailView.as_view(), name="detail"),
    path(
        "<int:job_resume_id>/interview/",
        InterviewResultCreateView.as_view(),
        name="interview",
    ),
    path("<int:pk>/candidate/", JobApplicationDetailView.as_view(), name="candidate"),
    path("companies/<int:company_id>/favorite/", FavoriteCompanyView.as_view(), name="favorite_company"),
    path("<int:company_id>/collect/", CollectCompanyView.as_view(), name="collect_company"),
    path('calendar/', CompanyInterviewsCalendarView.as_view(), name='calendar'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import CustomTemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.urls import path, include
import os

urlpatterns = [
    path(os.getenv("ADMIN_URL"), admin.site.urls),
    path("", CustomTemplateView.as_view(), name="home"),
    path("resumes/", include("resumes.urls")),
    path("users/", include("users.urls")),
    path("jobs/", include("jobs.urls")),
    path("companies/", include("companies.urls")),
    path("accounts/", include("allauth.urls")),
    path("educations/", include("educations.urls")),
    path("works/", include("works.urls")),
    path("projects/", include("projects.urls")),
    path("api/v1/resumes/",include("resumes.urls")),
    path("about/", include("about.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from resumes import views as resumes
from .views import (
    UserHomeView,
    UserLoginView,
    UserLogoutView,
    UserDetailView,
    UserUpdateView,
    UserRegisterView,
    UserPasswordChangeView,
    UserAddView,
    UserJobsView,
    ApplyForJobCreateView,
    ApplyForJobListView,
    WithdrawApplicationView,
    CollectJobView,
    InterviewResponseView,
    FavoriteCompaniesView,
    InterviewsCalendarView,
)

app_name = "users"

urlpatterns = [
    path("", UserHomeView.as_view(), name="home"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        UserPasswordChangeView.as_view(),
        name="password_change",
    ),
    path("<int:pk>/update/", UserUpdateView.as_view(), name="update"),
    path("<int:pk>/create/", UserAddView.as_view(), name="create"),
    path("<pk>/resumes/", resumes.ResumeArea.as_view(), name="resumes"),
    path("<int:job_id>/apply/", ApplyForJobCreateView.as_view(), name="apply"),
    path("<pk>/applied_jobs/", ApplyForJobListView.as_view(), name="applications"),
    path("<int:pk>/withdraw/", WithdrawApplicationView.as_view(), name="withdraw"),
    path("<int:pk>/", UserDetailView.as_view(), name="detail"),
    path("collect/", CollectJobView.as_view(), name="collect"),
    path("jobs/", UserJobsView.as_view(), name="jobs"),
    path('interview/<int:pk>/', InterviewResponseView.as_view(), name='interview'),
    path('calendar/', InterviewsCalendarView.as_view(), name='calendar'),
    path("favorites/", FavoriteCompaniesView.as_view(), name="favorites"),
]

companies/models.py
from django.db import models
from users.models import CustomUser


class Company(models.Model):
    company_name = models.CharField(max_length=100, default="")
    tin = models.CharField(max_length=8, default="")
    user_name = models.CharField(max_length=100, default="")
    tel = models.CharField(max_length=11, default="")
    custom_user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=250, default="")
    description = models.TextField(default="")
    type = models.CharField(max_length=50, default="")
    banner = models.ImageField(upload_to="banners/", null=True, blank=True)
    logo = models.ImageField(upload_to="logos/", null=True, blank=True)

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.company_name

class User_Company(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    collect = models.BooleanField(default=False)

companies/views.py
from django.contrib import messages
from django.contrib.auth import logout, login, get_backends
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template import Template, Context
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views import View
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import FormView, UpdateView
from django.views.generic.detail import DetailView
from jobs.models import Job_Resume, Job, User_Job
from .models import Company, User_Company
from .forms import CompanyRegisterForm, CompanyUpdateForm
from django.contrib.auth.models import AnonymousUser
import rules


def get_user_backend(user):
    for backend in get_backends():
        if backend.get_user(user.pk) is not None:
            return backend
    raise Exception("No backend found for user")


class CompanyRegisterView(FormView):
    template_name = "companies/register.html"
    form_class = CompanyRegisterForm

    def form_valid(self, form):
        user = form.save()
        backend = get_user_backend(user)
        messages.success(self.request, "註冊成功")
        login(
            self.request,
            user,
            backend=backend.__module__ + "." + backend.__class__.__name__,
        )
        return super(CompanyRegisterView, self).form_valid(form)

    def get_success_url(self):
        user = self.request.user

        try:
            company = Company.objects.get(custom_user=user)
        except Company.DoesNotExist:
            company = None

        if user.user_type == 2 and company is None:
            return reverse_lazy("users:create", kwargs={"pk": user.pk})
        else:
            return reverse_lazy("companies:home")


class CompanyHomeView(PermissionRequiredMixin, TemplateView):
    model = Company
    template_name = "companies/home.html"
    permission_required = "company_can_show"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        company = Company.objects.get(custom_user=self.request.user)
        context["company"] = company
        return context

class CompanyLoginView(LoginView):
    template_name = "companies/login.html"   
    
    def form_invalid(self, form):
        messages.error(self.request, "登入失敗")
        return super().form_invalid(form)
    
    def form_valid(self, form):
        messages.success(self.request, "登入成功")
        return super().form_valid(form)
        

    def get_default_redirect_url(self):
        user = self.request.user

        try:
            company = Company.objects.get(custom_user=user)
        except Company.DoesNotExist:
            company = None

        if user.user_type == 2 and company is None:
            return reverse_lazy("users:create", kwargs={"pk": user.pk})

        elif user.user_type == 1:
            logout(self.request)
            return reverse_lazy("users:login")

        else:
            return reverse_lazy("companies:home")


class CompanyLogoutView(PermissionRequiredMixin, LogoutView):
    next_page = reverse_lazy("home")
    permission_required = "company_can_show"

    def dispatch(self, request, *args, **kwargs):
        messages.success(self.request, "登出成功")
        return super().dispatch(request, *args, **kwargs)


class CompanyDetailView(PermissionRequiredMixin, LoginRequiredMixin, DetailView):
    model = Company
    template_name = "companies/detail.html"
    context_object_name = "company"
    login_url = "/companies/"
    permission_required = "company_can_show"

    def dispatch(self, request, *args, **kwargs):
        self.company = self.get_object()
        if not rules.test_rule("is_current_company", request.user, self.company):
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.object.custom_user
        context["description"] = self.object.description
        return context


class CompanyUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Company
    form_class = CompanyUpdateForm
    template_name = "companies/update.html"
    context_object_name = "company"
    success_url = "/companies/"
    login_url = "/companies/"
    permission_required = "company_can_show"

    def get_queryset(self):
        user = self.request.user
        queryset = Company.objects.filter(custom_user=user, custom_user__user_type=2)
        return queryset

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["company"] = self.object
        context["user"] = self.object.custom_user
        return context

    def form_valid(self, form):
        messages.success(self.request, "更新成功")
        return super().form_valid(form)

class CompanyPasswordChangeView(PermissionRequiredMixin, PasswordChangeView):
    template_name = "companies/password_change_form.html"
    success_url = "/companies/"
    permission_required = "company_can_show"

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse("companies:login"))
        return super().handle_no_permission()

    def form_valid(self, form):
        messages.success(self.request, "更新成功")
        response = super().form_valid(form)
        logout(self.request)
        return response


class CompanyListView(ListView):
    model = Company
    template_name = "companies/list.html"
    context_object_name = "companies_list"

    def get_queryset(self):
        queryset = Company.objects.all()
        search_keyword = self.request.GET.get("q")
        if search_keyword:
            queryset = queryset.filter(company_name__icontains=search_keyword)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            favorite_company_ids = User_Company.objects.filter(
                user=self.request.user, collect=True
            ).values_list("company_id", flat=True)
            context["user_companies"] = favorite_company_ids
        else:
            context["user_companies"] = []
        return context
    
    def render_to_response(self, context, **response_kwargs):
        if self.request.headers.get('HX-Request'):
            return render(self.request, 'companies/filter_company.html', context=context)
        return super().render_to_response(context, **response_kwargs)


class CompanyInfoView(DetailView):
    model = Company
    template_name = "companies/info.html"
    context_object_name = "company"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = self.object.address[:3]
        context["address"] = self.object.address[3:]
        context["job_count"] = self.object.jobs.count()
        context["jobs"] = self.object.jobs.all()

        if isinstance(self.request.user, AnonymousUser):
            context["user_jobs"] = []
        else:
            collected_jobs = User_Job.objects.filter(user=self.request.user).values_list('job_id', flat=True)
            context["user_jobs"] = list(collected_jobs)
            
        return context


class JobApplicationsView(ListView):
    model = Job_Resume
    template_name = "companies/apply.html"

    def get_queryset(self):
        company = get_object_or_404(Company, custom_user=self.request.user)
        return Job_Resume.objects.filter(job__company=company)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        company = get_object_or_404(Company, custom_user=self.request.user)
        company_jobs = Job.objects.filter(company=company)
        job_resume_dict = {}
        for job in company_jobs:
            job_resume_dict[job] = Job_Resume.objects.filter(job=job)
        context["job_resume_dict"] = job_resume_dict
        context["company"] = self.request.user.company
        return context

    def form_valid(self, form):
        job_resume_id = self.request.POST.get("job_resume_id")
        job_resume = get_object_or_404(Job_Resume, pk=job_resume_id)

        interview_date = form.cleaned_data["interview_date"]
        interview_invitation = form.cleaned_data["interview_invitation"]

        invitation_template = Template(interview_invitation)
        context = Context(
            {
                "job_resume": job_resume,
                "interview_date": interview_date,
                "company": self.request.user.company,
            }
        )
        job_resume.interview_invitation = invitation_template.render(context)
        job_resume.interview_date = interview_date
        job_resume.save()
        return super().form_valid(form)


class JobApplicationDetailView(DetailView):
    model = Job_Resume
    context_object_name = "company"


    def get_template_names(self):
        return ["resumes/base_template.html"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        job_resume = self.get_object()
        resume = job_resume.resume
        resume_data = [resume]
        education_data = resume.educations.all()
        work_data = resume.works.all()
        project_data = resume.projects.all()

        context["total_data"] = {
            "resume_data": resume_data,
            "education_data": education_data,

templates/companies/apply.html
{% extends 'backend.html' %}
{% block content %}
<br>
{% for job, resumes in job_resume_dict.items %}
    <h2 class="text-3xl font-semibold mb-4 text-center">{{ job.company.company_name }} {{ job.title }}</h2>
    <div class="flex flex-wrap">
        {% for job_resume in resumes %}
            <div class="w-full md:w-1/2 lg:w-1/3 px-4 mb-6">
                <div class="bg-white p-6 shadow-lg rounded-lg flex flex-col justify-between h-full">
                    <div>
                        <div class="flex justify-between items-center mb-4">
                            <div>
                                <p><strong>應徵者:</strong> {{ job_resume.resume.name }}</p>
                                <p><strong>應徵時間:</strong> {{ job_resume.created_at|date:"Y.m.d H:i" }}</p>
                            </div>
                            {% if job_resume.status == 'withdrawn' %}
                                <p class="text-red-500"><strong>求職者已取消應徵</strong> <br>{{ job_resume.withdrawn_at|date:"Y.m.d H:i" }}</p>
                            {% else %}
                                <div class="text-right">
                                    <a href="{% url 'companies:candidate' job_resume.pk %}" class="company-md-btn-full break-keep">履歷</a>
                                </div>
                            {% endif %}
                        </div>
                        {% if request.user == job_resume.job.company.custom_user %}
                            {% if job_resume.status == 'applied' %}
                                {% if not job_resume.read_at %}
                                    <form action="{% url 'companies:mark' job_resume.pk %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="company-md-btn-full break-keep">發送面試</button>
                                    </form>
                                {% else %}
                                    {% if job_resume.interview_date %}
                                        <p><small class="text-gray-600">面試時間: {{ job_resume.interview_date|date:"Y.m.d H:i" }}</small></p>
                                    {% else %}
                                        <form action="{% url 'companies:interview' job_resume.pk %}" method="post" class="mt-4">
                                            {% csrf_token %}
                                            <input type="hidden" name="job_resume_id" value="{{ job_resume.id }}">
                                            <label for="interview_date">面試日期:</label>
                                            <input type="datetime-local" name="interview_date" class="block w-full mt-2 p-2 border rounded-lg" required>
                                            <label for="interview_invitation" class="mt-2">面試信:</label>
                                            <textarea name="interview_invitation" rows="4" class="block w-full mt-2 p-2 border rounded-lg overflow-y-auto" required>
                                                親愛的 {{ job_resume.resume.name }}，
                                                                                            
                                                感謝您應徵 {{ job_resume.job.title }} 一職。經過初步篩選，我們很高興通知您進入了面試環節。
                                                                                            
                                                面試詳情如下：
                                                日期：<填寫面試日期>
                                                地點：<填寫面試地點>
                                                聯絡人：<{{ company.user_name }}>
                                                聯絡方式：<{{ company.tel }} , {{ user.email }}> 
                                                                                            
                                                請攜帶相關證件及資料準時參加面試。如有任何疑問，請隨時聯絡我們。
                                                                                            
                                                期待與您的面談！
                                                                                            
                                                此致
                                                {{ company.company_name }}          
                                            </textarea>
                                            <button type="submit" class="mt-4 px-4 py-2 bg-company-green text-white rounded-lg">發送面試邀請</button>
                                        </form>
                                    {% endif %}
                                    {% if job_resume.accepted ==  'accept' %}
                                        <p><small class="text-company-green">求職者同意參與此次面試</small></p>
                                    {% elif job_resume.accepted == 'reject' %}
                                        <p><small class="text-red-600">求職者拒絕此次面試</small></p>
                                    {% elif not job_resume.interview_date %}
                                    {% else %}
                                        <p><small class="text-gray-600">求職者尚未回覆</small></p>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <hr>
{% endfor %}
{% endblock %}

templates/companies/filter_company.html
{% load static %}
<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
    {% for company in companies_list %}
        <a href="{% url 'companies:company_info' company.id %}"><div class="flex flex-col justify-between h-full overflow-hidden bg-white rounded-lg shadow-md hover:shadow-xl">
            <div class="p-2">
                {% if company.banner %}
                    <div class="w-76 h-48 overflow-hidden rounded-md">
                        <img src="{{ company.banner.url }}" alt="{{ company.company_name }}" class="object-cover w-full h-full">
                    </div>
                {% else %}
                    <div class="w-76 h-48 overflow-hidden rounded-md">
                        <img src="{% static 'img/company.jpg' %}" alt="{{ company.company_name }}" class="object-cover w-full h-full">
                    </div>
                {% endif %}
            </div>
            <div class="flex-grow p-4">

                <div class="flex items-center mb-4">
                    {% if company.logo %}
                        <div class="w-5 h-5 mr-2 rounded-full overflow-hidden">
                            <img src="{{ company.logo.url }}" alt="{{ company.company_name }}" class="w-full h-full object-cover">
                        </div>
                    {% else %}
                    <div class="w-5 h-5 mr-2 rounded-full overflow-hidden">
                        <img src="{% static 'img/company.jpg' %}" alt="{{ company.company_name }}" class="w-full h-full object-cover">
                    </div>
                    {% endif %}
                    <h2 class="text-xl font-semibold truncate">{{ company.company_name }}</h2>
                </div>
                <div class="card-description min-h-[3rem]">
                    <p class="text-gray-600 line-clamp-3">{{ company.description }}</p>
                </div>
            </div>
            <div class="flex-shrink-0 p-4">
                <div class="flex items-center justify-between">
                    <div class="flex items-center">
                        <i class="w-4 h-4 mr-1 text-gray-500 fa-solid fa-location-dot"></i>
                        <p class="flex items-center text-xs text-gray-600">{{ company.address|slice:":3" }}</p>
                        <i class="w-4 h-4 ml-3 mr-1 text-gray-500 fa-solid fa-briefcase"></i>
                        <p class="flex items-center text-xs text-gray-600">{{ company.type }}</p>
                    </div>
                    {% if request.user.user_type == 1 %}
                        <form action="{% url 'companies:favorite_company' company.id %}" method="post" class="inline" hx-post="{% url 'companies:favorite_company' company.id %}" hx-target="#collect-company-button-{{ company.id }}" hx-swap="outerHTML">                                                                       
                            {% csrf_token %}
                            <input type="hidden" name="company_id" value="{{ company.id }}">
                            {% include 'shared/collect_company.html' %}
                        </form>
                    {% endif %}
                </div>
            </div>
        </div></a>
    {% endfor %}
</div>

templates/companies/info.html
{% extends "backend.html" %}
{% load humanize %}
{% load static %}
{% block content %}
<div class="container w-screen min-h-screen p-4 mx-auto">
    <div class="p-6 bg-white rounded-lg shadow-lg">
        <div class="flex items-center mb-6">
            {% if company.logo %}
                <img src="{{ company.logo.url }}" alt="{{ company.company_name }}" class="w-16 h-16 mr-4 rounded-full">
            {% else %}
                <img src="{% static 'img/company.jpg' %}" alt="{{ company.company_name }}" class="w-16 h-16 mr-4 rounded-full">
            {% endif %}
            <h1 class="text-2xl font-semibold">{{ company.company_name }}</h1>
        </div>
        <div class="mb-4">
            <p>{{ company.description }}</p>
        </div>
        <div class="mb-6">
            <ul class="list-none">
                <li class="flex items-center mb-2">
                    <i class="w-4 h-4 text-gray-500 fa-solid fa-location-dot"></i>
                    <span class="ml-2">{{ company.address }}</span>
                    <a href="https://www.google.com/maps/search/?api=1&query={{ company.address }}" target="_blank" class="inline-flex items-center ml-2 text-user-blue">
                        <i class="fa-solid fa-arrow-up-right-from-square"></i>
                    </a>
                </li>
                <li class="flex items-center mb-2">
                    <i class="w-4 h-4 text-gray-500 fa-solid fa-briefcase"></i>
                    <span class="ml-2">{{ company.type }}</span>
                </li>
            </ul>
        </div>
        <div class="text-center">
            <a href="#job-list" class="inline-block px-4 py-2 text-white bg-user-blue rounded-md hover:bg-white hover:border-user-blue hover:text-user-blue border">查看職缺 ({{ job_count }})</a>
        </div>
    </div>

    <div class="mt-8">
        <h2 id="job-list" class="mb-4 text-xl font-semibold scroll-mt-16">職缺列表</h2>
        <div class="space-y-6">
            {% if jobs %}
                {% for job in jobs %}
                    <div class="flex flex-col items-start justify-between p-4 bg-white rounded-lg shadow-lg md:flex-row md:items-center">
                        <div class="w-64 mb-4 md:w-1/3 md:mb-0 md:mr-4">
                            {% if job.company.banner %}
                                <img src="{{ job.company.banner.url }}" alt="公司圖片" class="object-cover w-full h-full rounded">
                            {% else %}
                                <img src="{% static 'img/company_banner.webp' %}" alt="預設公司圖片" class="object-cover w-full h-full rounded">
                            {% endif %}
                        </div>
                        <div class="flex flex-col items-start justify-between w-full space-y-4 md:w-2/3 md:flex-row md:items-center md:space-y-0">
                            <div class="flex flex-col flex-grow space-y-4 md:mr-4">
                                <h2 class="pl-4 text-2xl font-bold">{{ job.title }}</h2>
                                <div class="flex items-center pl-4 space-x-2">
                                    {% if company.logo %}
                                        <img src="{{ job.company.logo.url }}" alt="公司Logo" class="object-cover w-6 h-6 rounded">
                                    {% else %}
                                        <img src="{% static 'img/company.jpg' %}" alt="{{ company.company_name }}" class="w-16 h-16 mr-4 rounded-full">
                                    {% endif %}
                                    <p class="text-lg">{{ job.company.company_name }}</p>
                                </div>
                                <div class="flex items-center space-x-2">
                                    <i class="w-4 h-4 text-gray-500 fa-solid fa-location-dot"></i> 
                                    <p class="text-gray-700">{{ job.address|slice:":3" }}</p>
                                    <i class="w-4 h-4 text-gray-500 fa-solid fa-sack-dollar"></i>
                                    <p class="text-gray-700">NT${{ job.salary|intcomma }}</p>
                                </div>
                            </div>
                            <div class="flex flex-row items-center justify-end w-full mt-4 space-x-4 md:flex-col md:items-start md:w-auto md:space-x-0 md:space-y-4 md:mt-0 md:flex-shrink-0">
                                {% if request.user.user_type == 1 %}
                                    <a href="{% url 'users:apply' job.id %}" class="px-4 py-2 text-white bg-user-blue rounded-md hover:bg-white hover:border-user-blue hover:text-user-blue border">立即應徵</a>
                                    <form action="{% url 'users:collect' %}" method="post" class="inline" hx-post="{% url 'users:collect' %}" hx-target="#collect-button-{{ job.id }}" hx-swap="outerHTML">
                                        {% csrf_token %}
                                        <input type="hidden" name="job_id" value="{{ job.id }}">
                                        {% include 'shared/collect_btn.html' %}
                                    </form>
                                {% else %}
                                    <a href="{% url 'users:login' %}" class="px-4 py-2 text-white bg-user-blue rounded-md hover:bg-white hover:border-user-blue hover:text-user-blue border">立即應徵</a>
                                    <a href="{% url 'users:login' %}" class="px-4 py-2 text-white bg-user-blue rounded-md hover:bg-white hover:border-user-blue hover:text-user-blue border">收藏職缺</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <br>
                <p class="text-xl text-center">該公司尚未有合適職缺。</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/companies/list.html
{% extends 'backend.html' %}
{% load static %}
{% block content %}
    <header class="sticky z-10 w-full py-8 text-center bg-blue-50 top-16">
        <div class="container px-4 mx-auto">
            <h1 class="text-2xl font-bold">拓展求職視野，尋找理想工作</h1>
            <div class="flex flex-wrap justify-center mt-6">
                <form action="{% url 'companies:company_list' %}" method="get" class="flex w-full md:w-2/3" hx-get="{% url 'companies:company_list' %}" hx-target="#company-list" hx-trigger="submit">
                    <input type="text" name="q" placeholder="搜尋公司名稱" class="flex-grow p-2 border border-gray-300 rounded-l-lg focus:outline-none focus:border-indigo-500" value="{{ request.GET.q|default:'' }}"/>
                    <button type="submit" class="p-2 text-white bg-user-blue rounded-r-lg">搜尋</button>
                    {% if request.GET.q %}
                        <a href="{% url 'companies:company_list' %}" class="p-2 ml-2 text-white bg-red-500 rounded-lg">取消搜尋</a>
                    {% endif %}
                </form>
            </div>
        </div>
    </header>
    <div class="container px-4 py-8 mx-auto" id="company-list">
        {% include 'companies/filter_company.html' with companies=companies jobs=jobs %}
    </div>
</div>
{% endblock %}