core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import CustomTemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.urls import path, include
import os

urlpatterns = [
    path(os.getenv("ADMIN_URL"), admin.site.urls),
    path("", CustomTemplateView.as_view(), name="home"),
    path("resumes/", include("resumes.urls")),
    path("users/", include("users.urls")),
    path("jobs/", include("jobs.urls")),
    path("companies/", include("companies.urls")),
    path("accounts/", include("allauth.urls")),
    path("educations/", include("educations.urls")),
    path("works/", include("works.urls")),
    path("projects/", include("projects.urls")),
    path("api/v1/resumes/",include("resumes.urls")),
    path("about/", include("about.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resumes/urls.py
from django.urls import path
from .views import (
    ResumeArea,
    ResumeListView,
    ResumeCreateView,
    ResumeUpdateView,
    ResumeDeleteView,
    TotalListView,
    generate_pdf_1,
    generate_pdf_2,
    generate_pdf_3,
    update_positions,
    UpdateStyleView,
    update_template,
)
from educations.views import EducationCreateView, EducationListView
from works.views import WorkCreateView, WorkListView
from projects.views import ProjectCreateView, ProjectListView

app_name = "resumes"

urlpatterns = [
    path("", ResumeArea.as_view(), name="index"),
    path("create/", ResumeCreateView.as_view(), name="create"),
    path("edit/<pk>", ResumeUpdateView.as_view(), name="edit"),
    path("delete/<pk>", ResumeDeleteView.as_view(), name="delete"),
    path("resume/<int:resume_id>/pdf_1/", generate_pdf_1, name="generate_pdf_1"),
    path("resume/<int:resume_id>/pdf_2/", generate_pdf_2, name="generate_pdf_2"),
    path("resume/<int:resume_id>/pdf_3/", generate_pdf_3, name="generate_pdf_3"),
    path("total/<int:resume_id>", TotalListView.as_view(), name="total"),
    path("update_positions/", update_positions, name="update_positions"),
    path("<pk>/education/", EducationCreateView.as_view(), name="education"),
    path("<pk>/educations/", EducationListView.as_view(), name="educations"),
    path("<pk>/work/", WorkCreateView.as_view(), name="work"),
    path("<pk>/works/", WorkListView.as_view(), name="works"),
    path("<pk>/project/", ProjectCreateView.as_view(), name="project"),
    path("<pk>/projects/", ProjectListView.as_view(), name="projects"),
    path("update_style/<int:resume_id>", UpdateStyleView.as_view(), name="update_style"),
    path("<int:resume_id>/update_template", update_template, name="update_template"),
    path("<pk>/", ResumeListView.as_view(), name="show"),
]

resumes/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.core.files.base import ContentFile
from PIL import Image
from io import BytesIO

User = settings.AUTH_USER_MODEL


class ResumeManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted_at=None)


class Resume(models.Model):
    GENDER_CHOICES = [
        ("M", "男"),
        ("F", "女"),
        ("N", "不透露"),
    ]
    EXPERIENCE_CHOICES = [
        ("1年以下", "一年以下"),
        ("3年以下", "三年以下"),
        ("3年以上", "三年以上"),
        ("5年以上", "五年以上"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    resume_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    birthday = models.DateField(null=True, blank=True)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    experience = models.CharField(
        max_length=20, choices=EXPERIENCE_CHOICES, null=True, blank=True
    )
    skills = models.CharField(max_length=200, null=True, blank=True)
    linkedin = models.URLField(null=True, blank=True)
    github = models.URLField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    deleted_at = models.DateTimeField(null=True)
    picture = models.FileField(null=True)
    posit = models.IntegerField(default=0)
    style = models.IntegerField(default=1)

    objects = ResumeManager()

    def delete(self):
        self.deleted_at = timezone.now()
        self.save()

    def get_skills(self):
        return self.skills

    def save(self, *args, **kwargs):
        if self.picture:
            img = Image.open(self.picture)
            max_size = (300, 300)
            img.thumbnail(max_size, Image.LANCZOS)
            thumb_io = BytesIO()
            img_format = "PNG" if img.mode == "RGBA" else "JPEG"
            img.save(thumb_io, format=img_format)
            thumb_io.seek(0)
            file_extension = "png" if img.mode == "RGBA" else "jpg"
            new_file_name = f"{self.picture.name.split('.')[0]}_thumb.{file_extension}"
            self.picture.save(new_file_name, ContentFile(thumb_io.read()), save=False)
        super().save(*args, **kwargs)

resumes/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import HttpResponse, JsonResponse, HttpResponseForbidden
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.shortcuts import get_object_or_404, render
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
)
from educations.models import Education
from projects.models import Project
from works.models import Work
from .forms import ResumeForm
from .models import Resume
import json
import rules
import docraptor
import os


class ResumeArea(PermissionRequiredMixin, TemplateView):
    template_name = "resumes/area.html"
    permission_required = "user_can_show"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_resumes = Resume.objects.filter(user=self.request.user)
        context["resumes"] = user_resumes
        context["count"] = user_resumes.count()
        return context

    def get_queryset(self):
        user = self.request.user
        return Resume.objects.filter(user=user)


class ResumeListView(DetailView):
    model = Resume
    template_name = "resumes/index.html"
    context_object_name = "resume"

    def dispatch(self, request, *args, **kwargs):
        resume_id = self.kwargs.get("pk")
        resume = get_object_or_404(Resume, pk=resume_id)
        if not rules.test_rule("is_resume_user", request.user, resume):
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        resume = get_object_or_404(Resume, pk=self.kwargs["pk"])
        context["resume"] = resume
        context["total_data"] = {
            "resume_data": [resume],
            "education_data": Education.edu_objects.filter(resume_id=resume.resume_id),
            "work_data": resume.works.all(),
            "project_data": resume.projects.all(),
        }
        return context


class ResumeCreateView(LoginRequiredMixin, CreateView):
    model = Resume
    form_class = ResumeForm
    template_name = "resumes/create.html"
    success_url = reverse_lazy("resumes:index")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "新增成功")
        return super().form_valid(form)


class ResumeUpdateView(UpdateView):
    model = Resume
    form_class = ResumeForm
    template_name = "resumes/update.html"
    success_url = reverse_lazy("resumes:index")

    def dispatch(self, request, *args, **kwargs):
        resume_id = self.kwargs.get("pk")
        resume = get_object_or_404(Resume, pk=resume_id)
        if not rules.test_rule("is_resume_user", request.user, resume):
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        resume = form.save(commit=False)
        resume.save()
        messages.success(self.request, "更新成功")
        return super().form_valid(form)


class ResumeDeleteView(DeleteView):
    model = Resume
    success_url = reverse_lazy("resumes:index")

    def dispatch(self, request, *args, **kwargs):
        resume_id = self.kwargs.get("pk")
        resume = get_object_or_404(Resume, pk=resume_id)
        if not rules.test_rule("is_resume_user", request.user, resume):
            return HttpResponseForbidden()
        response = super().dispatch(request, *args, **kwargs)
        messages.success(self.request, "刪除成功")
        return response


class TotalListView(ListView):
    context_object_name = "total_data"

    def dispatch(self, request, *args, **kwargs):
        resume_id = self.kwargs.get("resume_id")
        resume = get_object_or_404(Resume, pk=resume_id)
        if not rules.test_rule("is_resume_user", request.user, resume):
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)

    def get_template_names(self):
        return ["resumes/base_template.html"]

    def get_queryset(self):
        resume_id = self.kwargs["resume_id"]
        resume_data = Resume.objects.filter(resume_id=resume_id)
        education_data = Education.objects.filter(resume_id=resume_id).order_by("posit")
        work_data = Work.objects.filter(resume_id=resume_id).order_by("posit")
        project_data = Project.objects.filter(resume_id=resume_id).order_by("posit")

        total_data = {
            "education_data": education_data,
            "work_data": work_data,
            "project_data": project_data,
            "resume_data": resume_data,
        }
        return total_data

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        resume_id = self.kwargs["resume_id"]
        user = self.request.user

        resume = get_object_or_404(Resume, pk=resume_id, user=user)
        education_data = Education.edu_objects.filter(resume_id=resume.resume_id)
        work_data = Work.objects.filter(resume_id=resume_id).order_by("posit")
        project_data = Project.objects.filter(resume_id=resume_id).order_by("posit")

        context["total_data"] = {
            "resume_data": [resume],
            "education_data": education_data,
            "work_data": work_data,
            "project_data": project_data,
        }
        context["is_total_page"] = True

        if self.request.user.user_type == 1:
            context["base_template"] = "frontend.html"
        elif self.request.user.user_type == 2:
            context["base_template"] = "backend.html"

        context["style_template"] = f"resumes/style{resume.style}.html"
        return context


def generate_pdf_1(request, resume_id):
    docraptor_client = docraptor.DocApi()
    docraptor_client.api_client.configuration.username = os.getenv("DOCRAPTOR_API_KEY")

    resume = get_object_or_404(Resume, pk=resume_id)
    user = resume.user

    total_data = {
        "resume_data": [resume],
        "education_data": Education.objects.filter(resume=resume),
        "work_data": Work.objects.filter(resume=resume),
        "project_data": Project.objects.filter(resume=resume),
    }

    html_string = render_to_string(
        "pdf_template1.html", {"user": user, "total_data": total_data}
    )

    response = docraptor_client.create_doc(
        {
            "document_content": html_string,
            "name": f"resume_{user.username}.pdf",
            "document_type": "pdf",
            "test": os.getenv("DOCRAPTOR_TEST")
        }
    )

    pdf_response = HttpResponse(response, content_type="application/pdf")
    pdf_response["Content-Disposition"] = (
        f'attachment; filename="resume_{user.username}.pdf"'
    )

    return pdf_response


def generate_pdf_2(request, resume_id):
    docraptor_client = docraptor.DocApi()
    docraptor_client.api_client.configuration.username = os.getenv("DOCRAPTOR_API_KEY")

    resume = get_object_or_404(Resume, pk=resume_id)
    user = resume.user

    total_data = {
        "resume_data": [resume],
        "education_data": Education.objects.filter(resume=resume),
        "work_data": Work.objects.filter(resume=resume),
        "project_data": Project.objects.filter(resume=resume),
    }

    html_string = render_to_string(
        "pdf_template2.html", {"user": user, "total_data": total_data}
    )

    response = docraptor_client.create_doc(
        {
            "document_content": html_string,
            "name": f"resume_{user.username}.pdf",
            "document_type": "pdf",
            "test": os.getenv("DOCRAPTOR_TEST")
        }
    )

    pdf_response = HttpResponse(response, content_type="application/pdf")
    pdf_response["Content-Disposition"] = (
        f'attachment; filename="resume_{user.username}.pdf"'
    )

    return pdf_response


def generate_pdf_3(request, resume_id):
    docraptor_client = docraptor.DocApi()
    docraptor_client.api_client.configuration.username = os.getenv("DOCRAPTOR_API_KEY")

    resume = get_object_or_404(Resume, pk=resume_id)
    user = resume.user

    total_data = {
        "resume_data": [resume],
        "education_data": Education.objects.filter(resume=resume),
        "work_data": Work.objects.filter(resume=resume),
        "project_data": Project.objects.filter(resume=resume),
    }

    html_string = render_to_string(
        "pdf_template3.html", {"user": user, "total_data": total_data}
    )

    response = docraptor_client.create_doc(
        {
            "document_content": html_string,
            "name": f"resume_{user.username}.pdf",
            "document_type": "pdf",
            "test": os.getenv("DOCRAPTOR_TEST")
        }
    )

    pdf_response = HttpResponse(response, content_type="application/pdf")
    pdf_response["Content-Disposition"] = (
        f'attachment; filename="resume_{user.username}.pdf"'
    )

    return pdf_response


def update_positions(request):
    if request.method == "POST":
        data = json.loads(request.body)
        positions = data.get("positions", [])

        for item in positions:
            obj_type = item.get("type")
            obj_id = int(item.get("id"))
            new_position = int(item.get("position"))

            if obj_type == "education":
                Model = Education
            elif obj_type == "work":
                Model = Work
            elif obj_type == "project":
                Model = Project
            else:
                continue

            obj = Model.objects.get(id=obj_id)
            obj.posit = new_position
            obj.save()
        return JsonResponse({"status": "success"})

templates/resumes/area.html
{% extends 'frontend.html' %}
{% block content %}
    <div class="container mx-auto flex flex-col justify-center items-center max-w-lg pt-16">
        <div class="header-bar flex justify-between items-center bg-user-blue text-white p-4 rounded-t-md w-full w-300px ">
            <div>
                <h1 class="text-2xl">Hello,{{ request.user|title }}</h1>
            </div>
            <a href="{% url 'resumes:create' %}" class="px-4 py-2 border-4 rounded-lg ml-2">&#43;建立履歷</a>
        </div>
        
        <div class="task-items-wrapper flex flex-col w-full border-user-blue border border-solid rounded-b-md shadow-md">
            <h2 class="text-lg font-semibold mb-4 mt-4 ml-4">我的履歷:</h2>
            {% if resumes %}
                {% for resume in resumes %}
                    <div class="task-wrapper flex justify-between items-center py-4 px-6 bg-white border-t border-gray-300 w-full rounded-md">
                        <a href="{% url 'resumes:show' pk=resume.pk %}" class="text-user-blue">{{ forloop.counter }}&nbsp;&nbsp;&nbsp;{{ resume.name }}</a>
                        <div class="flex space-x-4">
                            <a href="{% url 'resumes:total' resume_id=resume.pk %}" class="text-user-blue">預覽</a>
                            <form action="{% url 'resumes:delete' pk=resume.pk %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="text-user-blue">刪除</button>
                            </form>
                        </div>
                        
                    </div>
                {% endfor %}
            {% else %}
                <h3 class="text-lg mt-4 ml-4">目前無創建履歷</h3>
            {% endif %}
        </div>
        
        {% if resumes %}
            <h3 class="text-lg mt-4 ml-4">您目前已創建 <span class="font-bold">{{ resumes|length }}</span> 份履歷</h3>
        {% endif %}
    </div>
{% endblock %}

templates/resumes/base_template.html
{% extends base_template %}
{% load static %}
{% block content %}
    {% include style_template %}
{% endblock %}

templates/resumes/create.html
{% extends 'frontend.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container max-w-lg mx-auto mt-8">
        <div class="flex justify-center">
            <div class="w-full">
                <div class="flex items-center justify-start p-4 text-white bg-user-blue header-bar rounded-t-md">
                    <a href="{% url 'resumes:index' %}" class="text-white">&#8592;Back</a>
                </div>

                <div class="p-4 mt-4 shadow-md card-body" x-data>
                    <h3 class="mb-4 text-lg font-semibold">新增個人資料</h3>
                    <form method="post" id="myForm" action="{% url 'resumes:create' %}" enctype="multipart/form-data" @submit.prevent="showProcessingMessage($event)">
                        {% csrf_token %}
                        <div class="w-full md:w-2/3">
                            {% for field in form %}
                                {% if field.name == "picture" %}
                                    <div class="mb-4">
                                        <label class="block mb-2 text-sm font-bold text-gray-700" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                        <input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{ field.id_for_label }}" class="w-full p-2 border border-gray-300 rounded-md">
                                        <small class="text-gray-500">(只能上傳 .jpeg 圖片)</small>
                                        {% if field.errors %}
                                            <div class="mt-1 text-sm text-red-600">{{ field.errors }}</div>
                                        {% endif %}
                                    </div>
                                {% elif field.name == "address" %}
                                    <div class="mb-4">
                                        <label class="block mb-2 text-sm font-bold text-gray-700" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                        <input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{ field.id_for_label }}" class="w-full p-2 border border-gray-300 rounded-md">
                                        <small class="text-gray-500">請填入正確地址</small>
                                        {% if field.errors %}
                                            <div class="mt-1 text-sm text-red-600">{{ field.errors }}</div>
                                        {% endif %}
                                    </div>
                                {% else %}
                                    {{ field|as_crispy_field }}
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="mb-4 ml-4">
                            <div class="mb-2">
                                <div id="preview-container" class="hidden mt-4">
                                    <img id="preview" src="#" alt="Image Preview" class="border border-black w-72 h-72 object-contain" />
                                </div>
                            </div>
                        </div>
                        <div class="flex justify-end">
                            <button type="submit" class="user-sm-btn">提交</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/resumes/index.html
{% extends 'frontend.html' %}
{% load static %}
{% block content %}
    <div class="container mx-auto max-w-4xl mt-8">
        <div class="header-bar flex flex-wrap justify-between items-center bg-user-blue text-white p-4 rounded-t-md mb-4">
            <a href="{% url 'resumes:index' %}" class="text-white-600 hover:text-blue-200 mr-4">&#8592; Back</a>
            <div class="flex flex-col items-center md:flex-row">
                <a href="{% url 'resumes:edit' pk=resume.pk %}" class="text-white-600 hover:text-blue-200 mb-2 md:mr-4 md:mb-0">編輯&#43;</a>
                <a href="{% url 'resumes:educations' resume.resume_id %}" class="edu text-white-600 hover:text-blue-200 mb-2 md:mr-4 md:mb-0">教育經歷&#43;</a>
                <a href="{% url 'resumes:works' resume.resume_id %}" class="text-white-600 hover:text-blue-200 mb-2 md:mr-4 md:mb-0">工作經驗&#43;</a>
                <a href="{% url 'resumes:projects' resume.resume_id %}" class="text-white-600 hover:text-blue-200 mb-2 md:mr-4 md:mb-0">專案內容&#43;</a>
                <a href="{% url 'resumes:update_style' resume.resume_id %}" class="text-white-600 hover:text-blue-200 mb-2 md:mb-0">更換樣式&#43;</a>
            </div>
        </div>
        <div class="card-body p-4 shadow-md">
            <h1 class="text-3xl font-bold mb-6">我的個人資料</h1>
            <section id="resume-content">
                {% if resume.style == 1 %}
                    {% include "resumes/widget1.html" %}
                {% elif resume.style == 2 %}
                    {% include "resumes/widget2.html" %}
                {% else %}
                    {% include "resumes/widget3.html" %}
                {% endif %}
            </section>
        </div>
    </div>
{% endblock %}

templates/resumes/style1.html
<div class="container flex flex-col md:flex-row justify-center m-auto sm:my-10" style="display: flex; justify-content: center; width: 80%;">
    <div class="bg-blue-900 h-auto sm:p-8 p-4" style="background-color: #1e3a8a; box-sizing: border-box;
    flex-shrink: 0; height: auto;">
        {% for resume in total_data.resume_data %}
        {% if resume.picture %}
        <div class="flex items-center justify-center mb-8">
            <img src="{{ resume.picture.url }}" class="rounded-full w-32 border-2 h-32">
        </div>
        {% endif %}
        <h2 class="text-white text-xl font-bold">簡介</h2>
        <hr class="mb-4 w-1/6 bg-white h-0.5">
        <p class="text-white text-xl mb-2">{{ resume.name }}</p>
        <div class="flex justify-between">
            <p class="text-gray-400 text-base" style="color: #9ca3af;">{{ resume.get_gender_display }}</p>
            <p class="text-gray-400 text-base" style="color: #9ca3af;">{{ resume.birthday }}</p>
        </div>
        <p class="text-gray-400 text-base" style="color: #9ca3af;">{{ resume.address }}</p>
        <p class="text-gray-400 text-base" style="color: #9ca3af;">{{ resume.email }}</p>
        {% endfor %}
        <section class="drag-container mt-4">
            {% if total_data.education_data %}
            <h2 class="text-white text-xl font-bold">教育經驗</h2>
            <hr class="mb-5 w-1/6 bg-white h-0.5"></hr>
            {% for education in total_data.education_data %}
                <div class="my-4 drag" data-id="education-{{ education.id }}">
                    <p class="text-gray-400 text-xl" style="color: #9ca3af;">{{ education.school_name }}</p>
                    <p class="text-gray-400 text-base" style="color: #9ca3af;">{{education.major}} - <span text-gray-400 text-base>{{ education.get_degree_display }}</span></p>
                    <p class="text-gray-400 text-sm" style="color: #9ca3af";>{{ education.start_date}} - <span class="text-gray-400 text-sm" 
                        style="color: #9ca3af;">{{ education.end_date}}</span></p>
                </div>
            {% endfor %}
            {% endif %}
        </section>
        {% for resume in total_data.resume_data %}
        <h2 class="text-white text-xl font-bold">技能</h2>
        <hr class="mb-4 w-1/6 bg-white h-0.5"></hr>
        <div class="text-gray-400 text-base markdown-content" style="color: #9ca3af;">{{ resume.skills|linebreaksbr }}</div>
        {% endfor %}
    </div>
    <div class="bg-gray-100 md:w-[60%] w-full h-full sm:p-6" style="@media (min-width: 768px) {
        .custom-box {
            width: 40%;
        }
    } box-sizing: border-box; flex-grow: 1; height: auto;">
        <section class="drag-container">
            {% if total_data.project_data %}
            <h2 class="text-gray-700 text-xl">專案經驗</h2>
            <hr class="mb-5 w-1/6 bg-gray-700 h-1">
            {% for project in total_data.project_data %}
            <div class="mb-4 drag" data-id="project-{{ project.id }}">
                <p class="text-gray-700 text-lg font-bold">{{ project.project_name }}</p>
                <p class="text-gray-700 text-base">項目：<span class="text-gray-700">{{ project.responsibility }}
                </span></p>
                <p class="text-gray-700 text-base inline">技術：</p>
                {% for technology in project.get_technologies %}
                    <span class="text-gray-700">{{ technology }}</span>
                {% endfor %}
                <p class="text-gray-700 text-base leading-relaxed">說明：<span class="text-gray-700">{{project.description}}
                </span></p>
            </div>
            {% endfor %}
            {% endif %}
        </section>
        <section class="my-5 drag-container">
            {% if total_data.work_data %}
            <h2 class="text-gray-700 text-xl">工作經驗</h2>
            <hr class="mb-5 w-1/6 bg-gray-700 h-1">
            {% for work in total_data.work_data %}
            <div class="drag mt-2" data-id="work-{{ work.id }}">
                <h3 class="text-gray-700 text-lg">{{work.position}}</h3>
                <ul class="list-disc ml-4 text-gray-500">
                    <li>{{ work.company_name }}</li>
                    <li>{{ work.start_date}} - {{ work.end_date}}</li>
                </ul>
            </div>
            {% endfor %}
            {% endif %}
        </section>
    </div>
</div>
<div class="flex justify-evenly my-4">
    {% if is_total_page %}
    {% for resume in total_data.resume_data %}
    <a href="{% url 'resumes:generate_pdf_1' resume.resume_id %}" class="text-lg md:text-xl user-md-btn">下載PDF</a>
    {% endfor %}
    {% endif %}
</div>

templates/resumes/update.html
{% extends 'frontend.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mx-auto mt-8 max-w-lg">
    <div class="flex justify-center">
        <div class="w-full">
            <div class="header-bar bg-user-blue text-white flex items-center justify-start p-4 rounded-t-md">
                <a href="{% url 'resumes:show' pk=resume.pk %}" class="text-white">&#8592;Back</a>
            </div>
            <div class="card-body shadow-md p-4 mt-4">
                <h3 class="text-lg font-semibold mb-4">編輯個人信息</h3>
                <div x-data>
                    <form method="post" id="myForm" action="{% url 'resumes:edit' pk=resume.pk %}" enctype="multipart/form-data" class="flex flex-wrap" @submit.prevent="showProcessingMessage($event)">
                        {% csrf_token %}
                        <div class="w-full md:w-2/3">
                            {% for field in form %}
                                {% if field.name == "picture" %}
                                    <div class="mb-4">
                                        <label for="{{ field.id_for_label }}" class="block mb-2 text-sm font-bold text-gray-700">{{ field.label }}</label>
                                        <input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{ field.id_for_label }}" class="w-full p-2 border border-gray-300 rounded-md">
                                        <small class="text-gray-500">(只能上傳 .jpeg 圖片)</small>
                                        {% if field.errors %}
                                            <div class="mt-1 text-sm text-red-600">{{ field.errors }}</div>
                                        {% endif %}
                                    </div>
                                {% elif field.name == "address" %}
                                    <div class="mb-4">
                                        <label for="{{ field.id_for_label }}" class="block mb-2 text-sm font-bold text-gray-700">{{ field.label }}</label>
                                        <input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{ field.id_for_label }}" class="w-full p-2 border border-gray-300 rounded-md">
                                        <small class="text-gray-500">請填入正確地址</small>
                                        {% if field.errors %}
                                            <div class="mt-1 text-sm text-red-600">{{ field.errors }}</div>
                                        {% endif %}
                                    </div>
                                {% else %}
                                    <div class="mb-4 w-full">
                                        {{ field|as_crispy_field }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                            
                        <div id="preview-container" class="hidden mt-4 w-72 h-72">
                            <img id="preview" src="#" alt="Image Preview" class="border border-black w-72 h-72 object-contain" />
                        </div>
                        <div class="flex justify-end w-full mt-4 space-x-2">
                            <button type="submit" class="user-sm-btn">提交</button>
                            <button type="submit" form="deleteForm" class="user-sm-btn">刪除</button>
                        </div>
                    </form>
                </div>
                <form id="deleteForm" method="post" action="{% url 'resumes:delete' pk=resume.pk %}">
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}