core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import CustomTemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.urls import path, include
import os

urlpatterns = [
    path(os.getenv("ADMIN_URL"), admin.site.urls),
    path("", CustomTemplateView.as_view(), name="home"),
    path("resumes/", include("resumes.urls")),
    path("users/", include("users.urls")),
    path("jobs/", include("jobs.urls")),
    path("companies/", include("companies.urls")),
    path("accounts/", include("allauth.urls")),
    path("educations/", include("educations.urls")),
    path("works/", include("works.urls")),
    path("projects/", include("projects.urls")),
    path("api/v1/resumes/",include("resumes.urls")),
    path("about/", include("about.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from .views import (
    ShowView,
    EditView,
    JobDeleteView,
    PublishView,
    JobListView,
    JobDetailView,
)


app_name = "jobs"

urlpatterns = [
    path("list/", JobListView.as_view(), name="job_list"),
    path("detail/<pk>/", JobDetailView.as_view(), name="job_detail"),
    path("edit/<pk>/", EditView.as_view(), name="edit"),
    path("delete/<pk>/", JobDeleteView.as_view(), name="delete"),
    path("publish/<pk>", PublishView.as_view(), name="publish"),
    path("<pk>/", ShowView.as_view(), name="show"),
]

resumes/urls.py
from django.urls import path
from .views import (
    ResumeArea,
    ResumeListView,
    ResumeCreateView,
    ResumeUpdateView,
    ResumeDeleteView,
    TotalListView,
    generate_pdf_1,
    generate_pdf_2,
    generate_pdf_3,
    update_positions,
    UpdateStyleView,
    update_template,
)
from educations.views import EducationCreateView, EducationListView
from works.views import WorkCreateView, WorkListView
from projects.views import ProjectCreateView, ProjectListView

app_name = "resumes"

urlpatterns = [
    path("", ResumeArea.as_view(), name="index"),
    path("create/", ResumeCreateView.as_view(), name="create"),
    path("edit/<pk>", ResumeUpdateView.as_view(), name="edit"),
    path("delete/<pk>", ResumeDeleteView.as_view(), name="delete"),
    path("resume/<int:resume_id>/pdf_1/", generate_pdf_1, name="generate_pdf_1"),
    path("resume/<int:resume_id>/pdf_2/", generate_pdf_2, name="generate_pdf_2"),
    path("resume/<int:resume_id>/pdf_3/", generate_pdf_3, name="generate_pdf_3"),
    path("total/<int:resume_id>", TotalListView.as_view(), name="total"),
    path("update_positions/", update_positions, name="update_positions"),
    path("<pk>/education/", EducationCreateView.as_view(), name="education"),
    path("<pk>/educations/", EducationListView.as_view(), name="educations"),
    path("<pk>/work/", WorkCreateView.as_view(), name="work"),
    path("<pk>/works/", WorkListView.as_view(), name="works"),
    path("<pk>/project/", ProjectCreateView.as_view(), name="project"),
    path("<pk>/projects/", ProjectListView.as_view(), name="projects"),
    path("update_style/<int:resume_id>", UpdateStyleView.as_view(), name="update_style"),
    path("<int:resume_id>/update_template", update_template, name="update_template"),
    path("<pk>/", ResumeListView.as_view(), name="show"),
]

users/urls.py
from django.urls import path
from resumes import views as resumes
from .views import (
    UserHomeView,
    UserLoginView,
    UserLogoutView,
    UserDetailView,
    UserUpdateView,
    UserRegisterView,
    UserPasswordChangeView,
    UserAddView,
    UserJobsView,
    ApplyForJobCreateView,
    ApplyForJobListView,
    WithdrawApplicationView,
    CollectJobView,
    InterviewResponseView,
    FavoriteCompaniesView,
    InterviewsCalendarView,
)

app_name = "users"

urlpatterns = [
    path("", UserHomeView.as_view(), name="home"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        UserPasswordChangeView.as_view(),
        name="password_change",
    ),
    path("<int:pk>/update/", UserUpdateView.as_view(), name="update"),
    path("<int:pk>/create/", UserAddView.as_view(), name="create"),
    path("<pk>/resumes/", resumes.ResumeArea.as_view(), name="resumes"),
    path("<int:job_id>/apply/", ApplyForJobCreateView.as_view(), name="apply"),
    path("<pk>/applied_jobs/", ApplyForJobListView.as_view(), name="applications"),
    path("<int:pk>/withdraw/", WithdrawApplicationView.as_view(), name="withdraw"),
    path("<int:pk>/", UserDetailView.as_view(), name="detail"),
    path("collect/", CollectJobView.as_view(), name="collect"),
    path("jobs/", UserJobsView.as_view(), name="jobs"),
    path('interview/<int:pk>/', InterviewResponseView.as_view(), name='interview'),
    path('calendar/', InterviewsCalendarView.as_view(), name='calendar'),
    path("favorites/", FavoriteCompaniesView.as_view(), name="favorites"),
]

jobs/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator
from companies.models import Company
from resumes.models import Resume
from users.models import CustomUser


class JobManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(deleted_at=None)


OPENINGS_CHOICES = [(i, str(i)) for i in range(1, 11)]


def validate_taiwan_address(value):
    pass


class Job(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="jobs")
    title = models.CharField(max_length=100)
    openings = models.IntegerField(
        choices=OPENINGS_CHOICES,
        default=1,
        verbose_name="openings",
    )
    resumes = models.ManyToManyField(Resume, through="Job_Resume")
    users = models.ManyToManyField(CustomUser, through="User_Job")
    experience = models.PositiveIntegerField(validators=[MinValueValidator(0)])
    salary = models.PositiveIntegerField(blank=True, validators=[MinValueValidator(0)])
    address = models.CharField(max_length=250, default="")
    description = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True)
    is_published = models.BooleanField(default=False)

    objects = JobManager()

    def delete(self):
        self.deleted_at = timezone.now()
        self.save()


class Job_Resume(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, default="applied")
    withdrawn_at = models.DateTimeField(null=True, blank=True)
    read_at = models.DateTimeField(null=True, blank=True)
    interview_date = models.DateTimeField(null=True, blank=True)
    interview_invitation = models.TextField(null=True, blank=True)
    accepted = models.CharField(max_length=20, default=None, null=True)


class User_Job(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    collect = models.BooleanField(default=False)

jobs/forms.py
from django import forms
from django.forms import ModelForm
from .models import Job, Job_Resume


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = [
            "title",
            "openings",
            "experience",
            "salary",
            "address",
            "description",
            "is_published",
        ]
        labels = {
            "title": "職位名稱",
            "openings": "人數需求",
            "experience": "工作經驗",
            "salary": "工作薪資",
            "address": "工作地點",
            "description": "工作內容",
            "is_published": "是否刊登",
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super().__init__(*args, **kwargs)


class InterviewInvitationForm(forms.ModelForm):
    interview_date = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"})
    )
    interview_invitation = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Job_Resume
        fields = ["interview_date", "interview_invitation"]

    def __init__(self, *args, **kwargs):
        super(InterviewInvitationForm, self).__init__(*args, **kwargs)
        self.fields["interview_invitation"].initial = (
            "親愛的 {{ job_resume.resume.name }}，\n\n"
            "感謝您應徵 {{ job_resume.job.title }} 一職。經過初步篩選，我們很高興通知您進入了面試環節。\n\n"
            "面試詳情如下：\n"
            "日期：<填寫面試日期>\n"
            "地點：<填寫面試地點>\n"
            "聯絡人：<填寫聯絡人姓名及聯絡方式>\n\n"
            "請攜帶相關證件及資料準時參加面試。如有任何疑問，請隨時聯絡我們。\n\n"
            "期待與您的面談！\n\n"
            "此致\n"
            "{{ company.company_name }}"
        )


class InterviewResponseForm(forms.Form):
    ACCEPT = "accept"
    REJECT = "reject"

    RESPONSE_CHOICES = [
        (ACCEPT, "接受"),
        (REJECT, "拒絕"),
    ]

    response = forms.ChoiceField(
        choices=RESPONSE_CHOICES, widget=forms.RadioSelect, required=False
    )

jobs/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404
from .models import Job
from .forms import JobForm
from companies.models import Company
import rules
from jobs.models import User_Job

class IndexView(PermissionRequiredMixin,ListView):
    template_name = "jobs/index.html"
    model = Job
    context_object_name = "jobs"
    permission_required = "jobs.show_job"

    def dispatch(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        company = get_object_or_404(Company, pk=pk)
        if not rules.test_rule('is_current_company',request.user,company):
            return HttpResponseForbidden()
        return super().dispatch(request,*args, **kwargs)

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        company = get_object_or_404(Company, pk=pk)
        return Job.objects.filter(company=company)
        

class AddView(CreateView):
    template_name = "jobs/create.html"
    model = Job
    form_class = JobForm

    def dispatch(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        company = get_object_or_404(Company, pk=pk)
        if not rules.test_rule('is_current_company',request.user,company):
            return HttpResponseForbidden()
        return super().dispatch(request,*args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form):
        form.instance.company = get_object_or_404(Company, pk=self.kwargs.get("pk"))
        messages.success(self.request, "新增成功")
        self.success_url = reverse(
            "companies:jobs", kwargs={"pk": form.instance.company.pk}
        )
        return super().form_valid(form)


class ShowView(DetailView):
    template_name = "jobs/show.html"
    model = Job
    context_object_name = "job"


class EditView(UpdateView):
    model = Job
    form_class = JobForm
    template_name = "jobs/edit.html"
    context_object_name = "job"

    def form_valid(self, form):
        company_id = form.instance.company.id
        messages.success(self.request, "更新成功")
        self.success_url = reverse("companies:jobs", kwargs={"pk": company_id})
        return super().form_valid(form)

class JobDeleteView(DeleteView):
    model = Job
    
    def get_success_url(self):
        pk = self.object.company.pk
        messages.success(self.request, "刪除成功")
        return reverse("companies:jobs", kwargs={"pk": pk})
    
    def dispatch(self, request, *args, **kwargs):
        job = self.get_object()
        if not rules.test_rule('is_job_owner', request.user, job):
            return HttpResponseForbidden()
        return super().dispatch(request, *args, **kwargs)



class PublishView(DetailView):
    model=Job
    context_object_name = "job"
    template_name = "jobs/job.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_published = not self.object.is_published
        self.object.save()
        return render(request, "jobs/job.html", {"job":self.object})

class JobListView(ListView):
    model = Job
    template_name = 'jobs/list.html'
    context_object_name = 'jobs'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        job_list = []
        for job in context['jobs']:
            company = job.company
            job_info = {
                'title': job.title,
                'company_name': company.company_name,
                'company_logo_url': company.logo.url if company.logo else '',
                'company_banner_url': company.banner.url if company.banner else '',
                'address': job.address,
                'salary': job.salary,
                'description': job.description,
                'id': job.id
            }
            job_list.append(job_info)
        context['jobs'] = job_list
        if self.request.user.is_authenticated:
            user_jobs = User_Job.objects.filter(user=self.request.user).values_list('job_id', flat=True)
            context['user_jobs'] = list(user_jobs)
        return context
    
    def get_queryset(self):
        queryset = Job.objects.all()
        search_keyword = self.request.GET.get("q")
        if search_keyword:
            queryset = queryset.filter(title__icontains=search_keyword)
        return queryset
    
    def render_to_response(self, context, **response_kwargs):
        if self.request.headers.get('HX-Request'):
            return render(self.request, 'jobs/filter_job.html', context=context)
        return super().render_to_response(context, **response_kwargs)

class JobDetailView(DetailView):
    model = Job
    template_name = 'jobs/detail.html'
    context_object_name = 'job'

templates/jobs/apply.html
{% extends "backend.html" %}
{% load static %}
{% block content %}

<div class="flex justify-center items-center">
    <div class="max-w-lg w-full px-4 py-8 rounded-lg shadow-lg text-center">
        <img src="{% static 'img/resume.png' %}" alt="resume">
        <h1 class="text-2xl font-semibold mb-4">使用者：{{ request.user }}</h1>
        <h2 class="text-xl font-semibold mb-4">投遞工作：{{ job.title }}</h2>
        <form method="post" action="{% url 'users:apply' job.id %}" class="mb-4">
            {% csrf_token %}
            <input type="hidden" name="job_id" value="{{ job.id }}">
            {% if resumes %}
                <label class="block mb-2">選擇履歷：</label>
                {% for resume in resumes %}
                <label class="inline-flex items-center mb-2">
                    <input type="radio" name="resume_id" value="{{ resume.resume_id }}" class="mr-2" {% if forloop.first %}checked{% endif %}>
                    <span>{{ resume.name }}</span>
                </label>
                {% endfor %}
                <div class="mt-4">
                    <button type="submit" class="user-md-btn-full">提交</button>
                </div>
            {% endif %}
        </form>
        {% if resumes|length == 0 %}
        <div>
            <p class="text-gray-700 mb-2">您還未創建任何履歷。</p>
            <a href="{% url 'resumes:index' %}" class="user-md-btn-full">創建履歷</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/jobs/create.html
{% extends "backend.html" %}
{% block content %}
    <div class="flex justify-center py-8 px-4 md:px-0">
        <div class="w-full sm:max-w-md md:max-w-lg p-6 mb-6 bg-white rounded-lg shadow-md md:p-6 md:mb-6">
            <h1 class="px-4 py-2 mb-6 text-2xl text-white text-center bg-company-green rounded">刊登職缺</h1>
            <form method="post" class="space-y-4">
                {% csrf_token %}
                <div class="space-y-4">
                    {% for field in form %}
                        <div class="flex items-center space-x-4">
                            <label class="block text-lg font-medium text-gray-700 min-w-max" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                            {% if field.field.widget.input_type == "checkbox" %}
                                <div class="flex items-center">
                                    <input type="checkbox" name="{{ field.html_name }}" id="{{ field.id_for_label }}" class="w-4 h-4">
                                    <label class="block ml-2 text-lg font-medium text-gray-700" for="{{ field.id_for_label }}"></label>
                                </div>
                            {% elif field.label == "工作內容" %}
                                <textarea name="{{ field.html_name }}" id="{{ field.id_for_label }}" class="w-full h-32 p-2 border border-gray-300 rounded-md">{{ field.value|default_if_none:'' }}</textarea>
                            {% elif field.label == "人數需求" %}
                                <div class="flex items-center w-full space-x-2">
                                    <input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" value="{{ field.value|default_if_none:'' }}" id="{{ field.id_for_label }}" class="w-full p-2 border border-gray-300 rounded-md" placeholder="人">
                                </div>
                            {% elif field.label == "工作經驗" %}
                                <div class="flex items-center w-full space-x-2">
                                    <input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" value="{{ field.value|default_if_none:'' }}" id="{{ field.id_for_label }}" class="w-full p-2 border border-gray-300 rounded-md" placeholder="年">
                                </div>
                            {% elif field.label == "工作薪資" %}
                                <div class="flex items-center w-full space-x-2">
                                    <input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" value="{{ field.value|default_if_none:'' }}" id="{{ field.id_for_label }}" class="w-full p-2 border border-gray-300 rounded-md" placeholder="NT$xxxxx元">
                                </div>
                            {% else %}
                                <input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" value="{{ field.value|default_if_none:'' }}" id="{{ field.id_for_label }}" class="w-full p-2 border border-gray-300 rounded-md">
                            {% endif %}
                            {% if field.errors %}
                                <div class="mt-1 text-sm text-red-600">{{ field.errors }}</div>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <div class="flex justify-end mt-4">
                    <button type="submit" class="company-md-btn">新增職缺</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/jobs/detail.html
{% extends "backend.html" %}
{% load static %}
{% block content %}
<div class="max-w-2xl mx-auto py-8">
    <div class="bg-white shadow-lg rounded-lg p-6">
        <div class="flex items-center mb-4">
            <img src="{% static 'img/company.jpg' %}" alt="{{ company.company_name }}" class="object-cover w-6 h-6 rounded">
            <h1 class="text-2xl font-bold ml-4">{{job.title}}</h1>
        </div>
        <div class="flex items-center mb-2">
            <i class="fas fa-map-marker-alt text-gray-500"></i>
            <span class="text-gray-700">{{ job.address }}</span>
        </div>
        <div class="flex items-center mb-2">
            <i class="fas fa-dollar-sign text-gray-500"></i>
            <span class="text-gray-700">月薪 NT${{ job.salary }} 元</span>
        </div>
        <div class="mb-4">
            {% if request.user.user_type == 1 %}
            <h2 class="text-xl font-bold mb-2">工作內容：</h2>
            <p>{{job.description}}</p>
            {% else %}
            {% endif %}
        </div>
        <div class="flex justify-center">
            {% if request.user.user_type == 1 %}
            <a href="{% url 'users:apply' job.id %}" class="user-md-btn-full">立即應徵</a>
            {% else %}
            <p class="text-gray-700">想了解該筆職缺資訊嗎？立刻<a href="{% url 'users:login' %}" class="text-user-blue hover:underline">登入</a></p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/jobs/filter_job.html
{% load humanize %}
<div class="mx-auto space-y-6 md:w-4/5 lg:w-2/3">
    {% for job in jobs %}
        <div class="relative flex flex-col transition-shadow duration-300 bg-white rounded-lg shadow-lg hover:shadow-2xl md:flex-row">
            <a href="{% url 'jobs:job_detail' pk=job.id %}" class="w-76 h-36 md:w-1/3 m-2">
                <img src="{{ job.company_banner_url }}" alt="公司圖片" class="object-cover w-full h-full rounded-lg">
            </a>
            <a href="{% url 'jobs:job_detail' pk=job.id %}" class="flex flex-col justify-between p-4 space-y-4 md:flex-row md:space-y-0 md:items-center md:w-2/3">
                <div class="mb-16 flex-grow overflow-hidden md:flex md:flex-col md:justify-center md:max-w-full md:mb-0">
                    <h2 class="text-2xl font-bold truncate">{{ job.title }}</h2>
                    <div class="flex items-center mt-2 space-x-2">
                        <div class="w-6 h-6 mr-2 rounded-full overflow-hidden">
                            <img src="{{ job.company_logo_url }}" alt="公司Logo" class="object-cover w-full h-full">
                        </div>
                        <p class="max-w-full text-lg truncate">{{ job.company_name }}</p>
                    </div>
                    <div class="flex items-center mt-2 space-x-2">
                        <i class="w-4 h-4 text-gray-500 fa-solid fa-location-dot"></i> 
                        <p class="text-gray-700">{{ job.address|slice:":3" }}</p>
                        <i class="w-4 h-4 text-gray-500 fa-solid fa-sack-dollar"></i>
                        <p class="text-gray-700">NT${{ job.salary|intcomma }}</p>
                    </div>
                </div>
                <div class="absolute bottom-5 right-4 flex justify-end flex-shrink-0 space-x-4 md:justify-center md:flex-col md:items-end md:space-y-4 md:space-x-0 md:bottom-2">
                    {% if request.user.user_type == 1 %}
                    <a href="{% url 'users:apply' job.id %}" class="user-md-btn-full">
                        立即應徵
                    </a>                            
                    <form action="{% url 'users:collect' %}" method="post" class="inline" hx-post="{% url 'users:collect' %}" hx-target="#collect-button-{{ job.id }}" hx-swap="outerHTML">
                        {% csrf_token %}
                        <input type="hidden" name="job_id" value="{{ job.id }}">
                        {% include 'shared/collect_btn.html' %}
                    </form>
                    {% else %}
                    <div class="text-right">
                        <a href="{% url 'users:login' %}" class="text-user-blue hover:underline">立即登入</a>
                        <p class="text-gray-700">有找到合適職缺嗎？</p>
                        <p class="text-gray-700">EngiLink協助您找到更多心儀職缺！</p>
                    </div>
                    {% endif %}
                </div>
            </a>
        </div>
    {% endfor %}
</div>

templates/jobs/index.html
{% extends "backend.html" %}
{% block content %}
    <div class="pt-18">
        <div class="w-full bg-white">
            <div class="flex justify-center mt-1 space-x-2">
            </div>
        </div>
        <section class="container flex flex-wrap justify-center px-4 py-4 mx-auto mt-5">
            <div class="flex flex-wrap justify-start w-full max-w-screen-lg">
                {% for job in jobs %}
                    <div id="publish-{{ job.id }}" class="w-full p-4 sm:w-full md:w-1/2 lg:w-1/2 xl:w-1/2">
                        {% include "jobs/job.html"%}
                    </div>   
                {% endfor %}
            </div>
        </section>
    </div>
{% endblock %}

templates/jobs/job.html
{% load humanize %}
<div class="p-6 bg-white rounded-lg shadow-md">
    <h2 class="mb-4 text-2xl font-bold">{{ job.title }}</h2>
    <p class="mb-2"><span class="font-semibold">需求人數：</span>{{ job.openings }}人</p>
    <p class="mb-2"><span class="font-semibold">工作年資：</span>{{ job.experience }}年</p>
    <p class="mb-2"><span class="font-semibold">工作薪資：</span>月薪NT${{ job.salary|intcomma }}元</p>
    <p class="mb-2"><span class="font-semibold">工作地點：</span>{{ job.address }}</p>
    <p class="mb-4"><span class="font-semibold">工作描述：</span>{{ job.description }}</p>
    <div class="flex items-center justify-between">
        <form class="flex-1">
            {% csrf_token %}
            <button type="button"
                    hx-post="{% url 'jobs:publish' job.id %}"
                    hx-swap="innerHTML"
                    hx-target="#publish-{{ job.id }}"
                    class="w-full py-2 px-4 rounded-md {% if job.is_published %}bg-company-green text-white{% else %}bg-white text-company-green border-company-green border{% endif %}">
                {{ job.is_published | yesno:"刊登中,未上架" }}
            </button>
        </form>
        <div class="ml-4">
            <a href="{% url 'jobs:show' job.id %}" class="company-md-btn">編輯</a>
        </div>
    </div>
</div>

templates/jobs/list.html
{% extends "backend.html" %} {% load humanize %} {% block content %}
<header class="sticky z-10 w-full py-8 text-center bg-blue-50 top-16">
    <div class="container px-4 mx-auto">
        <h1 class="text-2xl font-bold">拓展求職視野，尋找理想工作</h1>
        <div class="flex flex-wrap justify-center mt-6">
            <form action="{% url 'jobs:job_list' %}" method="get" class="flex w-full md:w-2/3" hx-get="{% url 'jobs:job_list' %}" hx-target="#job-list" hx-trigger="submit">
                <input type="text" name="q" placeholder="搜尋職缺名稱" class="flex-grow p-2 border border-gray-300 rounded-l-lg focus:outline-none focus:border-indigo-500" value="{{ request.GET.q|default:'' }}"/>
                <button type="submit" class="p-2 text-white bg-user-blue rounded-r-lg">搜尋</button>
                {% if request.GET.q %}
                    <a href="{% url 'jobs:job_list' %}" class="p-2 ml-2 text-white bg-red-500 rounded-lg">取消搜尋</a>
                {% endif %}
            </form>
        </div>
    </div>
  </div>
</header>
<div>
    <div class="container px-4 py-8 mx-auto" id="job-list">
        {% include 'jobs/filter_job.html' with companies=companies jobs=jobs %}
    </dir>
{% endblock %}

templates/jobs/show.html
{% extends "backend.html" %}
{% load humanize %}
{% block content %}
    <div class="flex justify-center py-8">
        <div class="w-full max-w-lg p-6 mb-6 bg-white rounded-lg shadow-md">
            <p class="mb-4 text-lg font-bold">職位名稱：{{ job.title }}</p>
            <p class="mb-2"><span class="font-semibold">需求人數：</span>{{ job.openings }}人</p>
            <p class="mb-2"><span class="font-semibold">工作年資：</span>{{ job.experience }}年</p>
            <p class="mb-2"><span class="font-semibold">工作薪資：</span>月薪NT${{ job.salary|intcomma  }}元</p>
            <p class="mb-2"><span class="font-semibold">工作地點：</span>{{ job.address }}</p>
            <p class="mb-4"><span class="font-semibold">工作描述：</span>{{ job.description }}</p>
            
            <div class="flex justify-end space-x-4">
                <button class="company-md-btn-full">
                    <a href="{% url 'jobs:edit' job.id %}">修改</a>
                </button>

                <form action="{% url 'jobs:delete' job.id %}" method="post" class="inline-block">
                    {% csrf_token %}
                    <button class="company-md-btn">刪除</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}